#!/usr/bin/env python
# encoding: utf-8

import os, string, os.path

top = "."
out = "waf-build"


def options(ctx):
    ctx.load("gcc")

def configure(ctx):
    ctx.load("gcc")

def build(ctx):
    ctx.recurse(["src"])

